version: '3'

services:

  app:
    #image: codeeducation/keycloak:11.0.2-fix-translate
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: micro-auth-app-prod
    entrypoint: /opt/jboss/tools/docker-entrypoint.sh
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      #- KEYCLOAK_DEFAULT_THEME=codeflix
      - KEYCLOAK_IMPORT=/tmp/test-realm-export.json
    volumes:
      - ./keycloak/test-realm-export.json:/tmp/test-realm-export.json
    ports:
      - 8080:8080
    depends_on:
      - test
    networks:
      default:
        aliases:
          - app.test
  
  test:
    build: 
      context: ./tests
      args:
        - UID=${UID}
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-auth-test-prod
    volumes:
      - ./tests:/home/node/app
    depends_on:
      - selenium
    networks:
      - default

  selenium:
    image: selenium/standalone-chrome:88.0.4324.150-chromedriver-88.0.4324.96
    networks:
      - default
    #ports:
    #  - 4444:4444

  dockerize:
    image: jwilder/dockerize
    entrypoint: dockerize -wait tcp://app:8080 -timeout 200s
    networks:
      - default

networks:
  default:
    driver: bridge