version: '3'

services:

  app:
    #image: codeeducation/keycloak:11.0.2-fix-translate
    build: .
    container_name: micro-auth-app-test
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s /opt/jboss/tools/docker-entrypoint.sh
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      #- KEYCLOAK_IMPORT=realm-export.json
      - DB_ADDR=db
      - DB_VENDOR=mysql
      - DB_DATABASE=micro_atuh
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - 8080:8080
    volumes:
        - ./keycloak/config/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
        - ./frontend/build/codeflix:/opt/jboss/keycloak/themes/codeflix
        # - ./themes/keycloak:/opt/jboss/keycloak/themes/keycloak
        # - ./themes/base:/opt/jboss/keycloak/themes/base
    depends_on: 
      - db

  db:
    build: ./keycloak/.docker/mysql
    container_name: micro-auth-db-test
    restart: always
    tty: true
    ports:
      - "33007:3306"
    volumes:
      - ./keycloak/.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=micro_atuh
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
  
  frontend:
    build: ./frontend
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-auth-frontend-test
    volumes:
      - ./frontend:/home/node/app
  
  test:
    build: ./tests
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-auth-test-test
    volumes:
      - ./tests:/home/node/app

  selenium:
    image: selenium/standalone-chrome
